package com.example.seckill.dao;

import com.example.seckill.dataObject.OrderInfoDo;

public interface OrderInfoDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat Nov 07 23:26:56 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat Nov 07 23:26:56 CST 2020
     */
    int insert(OrderInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat Nov 07 23:26:56 CST 2020
     */
    int insertSelective(OrderInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat Nov 07 23:26:56 CST 2020
     */
    OrderInfoDo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat Nov 07 23:26:56 CST 2020
     */
    int updateByPrimaryKeySelective(OrderInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat Nov 07 23:26:56 CST 2020
     */
    int updateByPrimaryKey(OrderInfoDo record);
}