package com.example.seckill.dao;

import com.example.seckill.dataObject.SequenceInfoDo;

public interface SequenceInfoDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun Nov 08 00:13:48 CST 2020
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun Nov 08 00:13:48 CST 2020
     */
    int insert(SequenceInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun Nov 08 00:13:48 CST 2020
     */
    int insertSelective(SequenceInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun Nov 08 00:13:48 CST 2020
     */
    SequenceInfoDo selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun Nov 08 00:13:48 CST 2020
     */
    int updateByPrimaryKeySelective(SequenceInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun Nov 08 00:13:48 CST 2020
     */
    int updateByPrimaryKey(SequenceInfoDo record);

    SequenceInfoDo getSequenceByName(String name);
}